CREATE TABLE `financial_scenarios` (
	`id` int AUTO_INCREMENT NOT NULL,
	`propertyId` int NOT NULL,
	`userId` int NOT NULL,
	`scenarioName` varchar(100) NOT NULL,
	`strategyType` enum('rental','flip','brrrr') NOT NULL,
	`purchasePrice` int NOT NULL,
	`downPaymentPercent` int NOT NULL,
	`downPaymentAmount` int NOT NULL,
	`loanAmount` int NOT NULL,
	`interestRate` int NOT NULL,
	`loanTermYears` int NOT NULL,
	`closingCosts` int NOT NULL,
	`monthlyRent` int,
	`vacancyRate` int,
	`propertyManagementPercent` int,
	`monthlyInsurance` int,
	`monthlyPropertyTax` int,
	`monthlyHOA` int,
	`monthlyMaintenance` int,
	`renovationCost` int,
	`holdingMonths` int,
	`sellingCostsPercent` int,
	`afterRepairValue` int,
	`refinanceARV` int,
	`refinanceLTV` int,
	`refinanceRate` int,
	`monthlyMortgagePayment` int,
	`monthlyCashFlow` int,
	`annualCashFlow` int,
	`cashOnCashReturn` int,
	`capRate` int,
	`totalProfit` int,
	`roi` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `financial_scenarios_id` PRIMARY KEY(`id`)
);
